# questdb-fast-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: questdb-fast-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data/questdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-03

