apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onebailey-argocd-root
  namespace: cicd
spec:
  project: default
  source:
    repoURL: git@github.com:bigleaderman/one-bailey-infra.git
    targetRevision: main
    path: infra-deploy/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

