apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: data-pipeline
data:
  redis.conf: |
    # 최소 설정(비번은 args로 주입)
    bind 0.0.0.0
    protected-mode yes
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-use-rdb-preamble yes
    save 900 1
    save 300 10
    save 60 10000
    # 필요 시 메모리 정책
    # maxmemory 2gb
    # maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: data-pipeline
type: Opaque
stringData:
  REDIS_PASSWORD: "change-this-strong-pass"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: data-pipeline
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: data-pipeline
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: data-pipeline
  labels:
    app: redis
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        node-role.kubernetes.io/data-node: "true"   # worker-01으로 핀고정
      containers:
        - name: redis
          image: redis:7.2.4-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -lc
            - >
              exec redis-server /usr/local/etc/redis/redis.conf
              --appendonly yes
              --requirepass "$REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            exec:
              command: ["sh","-lc","redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh","-lc","redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
            - name: REDIS_ADDR
              value: "redis://localhost:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: REDIS_PASSWORD
          ports:
            - name: metrics
              containerPort: 9121
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
  namespace: data-pipeline
  labels:
    app: redis
    metrics: "true"
spec:
  selector:
    app: redis
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: data-pipeline
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
      metrics: "true"
  namespaceSelector:
    matchNames:
      - data-pipeline
  endpoints:
    - port: http-metrics
      interval: 15s
